export const
  TWO_PI = 2 * Math.PI,
  TWO_HALF_PI = TWO_PI - Math.PI / 2,
  FOURTH_PI = 0.78539816339,

  MUTATION_RATE = .01,
  AGENTS_COUNT = 100,
  AGENTS_RAND = ~~(AGENTS_COUNT * .1),
  TOP_AGENTS = ~~(AGENTS_COUNT * .3),
  BOT_AGENTS = ~~(AGENTS_COUNT * .08),

  TILE_SIZE = 3,
  PAD_W = 13,
  WIDTH = 70,
  HEIGHT = 110,

  SPEED = 100,

  BRICK_WID = 10,
  BRICK_HEI = 6,

  SCALE = 7;